In [1]:
import sys
import os
import pathlib
#sys.path.append('D:\\Documentos\\INNOVATE\lib\\FreeCAD\\bin')
pth=str(pathlib.Path().absolute())
general_repo="\\".join(pth.split('\\')[:5])
simetries_path=general_repo+"\\Simetrias\\Utils"

sys.path.append(simetries_path)

data_base_path="\\".join(pth.split('\\')[:3])+"\\Base_de_datos\\BEAMS\\Aceptado"

Hough_path=general_repo+"\\PCLHough"

sys.path.append(Hough_path)

import open3d as o3d
from Utilities import *
from MF import *
from hough3dlines import *

In [2]:
a=np.random.randint(-10,10,(1,3))
b=np.random.randint(-10,10,(1,3))
b=b/np.linalg.norm(b)
pp=np.vstack((a,b))
pp
list(np.vectorize(lambda x:list(x),otypes=[object],signature="(j)->()")(pp))

[[7.0, 5.0, -2.0],
 [-0.20739033894608505, -0.5184758473652127, -0.8295613557843402]]

In [24]:
def draw_line(a,b,L=100):
    p1=a+b*L
    p2=a+b*(-L)
    #print(p1)
    #print(p2)
    points=[p1.tolist(),p2.tolist()]
    #points=list(np.vectorize(lambda x:list(x),otypes=[object],signature="(j)->()")(pp))
    #print(points)
    line=[[0,1]]
    colors = [[1, 0, 0] for i in range(len(line))]
    line_set = o3d.geometry.LineSet()
    line_set.points = o3d.utility.Vector3dVector(points)
    line_set.lines = o3d.utility.Vector2iVector(line)
    line_set.colors = o3d.utility.Vector3dVector(colors)
    #o3d.visualization.draw_geometries([line_set])
    return line_set

In [28]:
pcds=os.listdir(data_base_path)
pcd=o3d.io.read_point_cloud(data_base_path+"\\"+pcds[10])

#NT = len(pcd.points)

#if NT >= 4096:
    #pcd = pcd.uniform_down_sample(int(NT/4096))
    
    
pcd.translate(-pcd.get_center())

#o3d.visualization.draw_geometries([pcd])
Z,XY=slices_(pcd, N = 5)

i=3
slice_points=np.hstack((np.array(XY[0]+XY[1]+XY[2]+XY[3]+XY[4]),
                        np.zeros((np.array(XY[0]+XY[1]+XY[2]+XY[3]+XY[4]).shape[0],1))))
slice_pcd=o3d.geometry.PointCloud()
slice_pcd.points=o3d.utility.Vector3dVector(slice_points)
o3d.visualization.draw_geometries([slice_pcd])

In [29]:
#line=draw_line(a,b,L=100)
o3d.visualization.draw_geometries([slice_pcd])
o3d.visualization.draw_geometries([pcd])

In [30]:
slice_pcd
fltd_slice_pcd, ind = slice_pcd.remove_statistical_outlier(nb_neighbors=40,
                                                    std_ratio=0.1)
o3d.visualization.draw_geometries([fltd_slice_pcd])

In [38]:
NT = len(pcd.points)
if NT >= 4096/16:
    fltd_slice_pcd = fltd_slice_pcd.uniform_down_sample(int(NT/(4096/16)))
o3d.visualization.draw_geometries([fltd_slice_pcd])

In [34]:
#A,B,n=hough3D_pcl(slice_pcd,opt_nlines=4,granularity=1/8)
A,B,n,vs=hough3D_pcl(slice_pcd,opt_nlines=4,granularity=1/8)

opt_dx
2.141983471464733
[]
[]
[1436 1691 1946 2201 2710 2965 3220 3475]
[36 36 36 36 36 36 36 36]
[37 37 37 37 37 37 37 37]
found 8 directions
[ 0.89442719 -0.4472136   0.        ]
[array([0.31022273, 0.22416852, 0.        ])]
[array([ 0.81800718, -0.57520801,  0.        ])]
[1402 1929 2982 3509]
[34 34 34 34]
[34 34 34 34]
found 4 directions
[ 0.83205029 -0.5547002   0.        ]
[array([0.31022273, 0.22416852, 0.        ]), array([ 1.28931052, -2.15224037,  0.        ])]
[array([ 0.81800718, -0.57520801,  0.        ]), array([ 0.84015338, -0.54234886,  0.        ])]
[1402 1929 2982 3509]
[34 34 34 34]
[34 34 34 34]
found 4 directions
[ 0.83205029 -0.5547002   0.        ]
[array([0.31022273, 0.22416852, 0.        ]), array([ 1.28931052, -2.15224037,  0.        ]), array([-10.89469106,   4.57201255,   0.        ])]
[array([ 0.81800718, -0.57520801,  0.        ]), array([ 0.84015338, -0.54234886,  0.        ]), array([ 0.8328365 , -0.55351907,  0.        ])]
[1402 1929 2982 3509]
[34 34

In [35]:
print(len(A))
print(A)
print(len(B))
print(B)
Ar=np.array(A)
Br=np.array(B)

4
[array([0.31022273, 0.22416852, 0.        ]), array([ 1.28931052, -2.15224037,  0.        ]), array([-10.89469106,   4.57201255,   0.        ]), array([ 2.1112016 , -4.97577339,  0.        ])]
4
[array([ 0.81800718, -0.57520801,  0.        ]), array([ 0.84015338, -0.54234886,  0.        ]), array([ 0.8328365 , -0.55351907,  0.        ]), array([ 0.83294889, -0.55334994,  0.        ])]


In [36]:
Ar=np.array(A)
Br=np.array(B)
Lines_arr=np.vectorize(draw_line,otypes=[object],signature="(j),(j),()->()")(Ar,Br,300)

In [37]:
o3d.visualization.draw_geometries(Lines_arr.tolist()+[slice_pcd])

In [5]:
vs.shape

(4912, 268, 268)

In [35]:
#Visualize VotingSpace
vs_pcd=o3d.geometry.PointCloud()
dx=np.arange(0,vs.shape[0])
dy=np.arange(0,vs.shape[1])
dz=np.arange(0,vs.shape[2])
n_vs=(vs+1)/np.max(vs+1)
#n_vs=n_vs[n_vs>0.5]

x,y,z=np.meshgrid(np.arange(0,n_vs.shape[0]),
                  np.arange(0,n_vs.shape[1]),
                  np.arange(0,n_vs.shape[2]))
p=np.hstack((x.reshape(-1,1),y.reshape(-1,1),z.reshape(-1,1)))

vs_pcd.points=o3d.utility.Vector3dVector(p*100)

colors=np.ones((p.shape[0],p.shape[1]+1))
colors[:,0]=n_vs[p[:,0],p[:,1],p[:,2]]
colors[:,1]=n_vs[p[:,0],p[:,1],p[:,2]]
vs_pcd.colors=o3d.utility.Vector3dVector(colors)

del x,y,z

o3d.visualization.draw_geometries([vs_pcd])

RuntimeError: 

In [13]:
colors=np.zeros(p.shape)
colors[:,0]=n_vs[p[:,0],p[:,1],p[:,2]]
slice_pcd.colors=o3d.utility.Vector3dVector(colors)

In [27]:
vs=np.random.randint(0,30,(4,3))
x,y=np.meshgrid(np.arange(0,vs.shape[0]),
                  np.arange(0,vs.shape[1]))#,
                  #np.arange(0,vs.shape[2]))
p=np.hstack((x.reshape(-1,1),y.reshape(-1,1)))#,z.reshape(-1,1)))
vs[p[:,0],p[:,1],p[:,2]]
print(vs)

[[25 24 21]
 [ 5 17 11]
 [13 16 16]
 [ 7 16  3]]


In [33]:
print(vs[p[:,0],p[:,1]].shape)
print(vs[p[:,0],p[:,1],p[:,2]])
vs[p[0,0],p[0,1]]

(12,)
[25  5 13  7 24 17 16 16 21 11 16  3]


25

In [33]:
p.shape

(22049968, 3)